import * as vscode from 'vscode';

export type MessageKey = keyof typeof englishMessages;

const englishMessages = {
    noSkillsFound: 'No skills found',
    initializeOrAddSkills: 'Initialize or add skills',
    files: 'files',
    path: 'Path',
    score: 'Score',
    size: 'Size',
    updated: 'Updated',
    issues: 'Issues',
    noSourcesConfigured: 'No sources configured',
    addSourceUrl: 'Add a source URL',
    cached: 'Cached',
    notFetched: 'Not fetched',
    agentsNotDetectedYet: 'Agents not detected yet',
    runDetectCommand: 'Run detect command',
    detected: 'Detected',
    notDetected: 'Not detected',
    noMcpServersDetected: 'No MCP servers detected',
    runDetectMcpServers: 'Run Detect MCP Servers',
    disabled: 'Disabled',
    enabled: 'Enabled',
    tool: 'Tool',
    command: 'Command',
    source: 'Source',
    noSkillsFoundTable: 'No skills found.',
    tags: 'Tags',
    delete: 'Delete',
    noSourcesConfiguredTable: 'No sources configured.',
    remove: 'Remove',
    agentsNotDetectedTable: 'Agents not detected yet.',
    noSyncRecordsYet: 'No sync records yet.',
    noMcpServersTable: 'No MCP servers detected. Run Detect MCP.',
    enable: 'Enable',
    disable: 'Disable',
    sync: 'Sync',
    refresh: 'Refresh',
    updateSources: 'Update Sources',
    installSkill: 'Install Skill',
    syncToAgents: 'Sync to Agents',
    detectAgents: 'Detect Agents',
    backup: 'Backup',
    openRepository: 'Open Repository',
    skills: 'Skills',
    skillsNeedingReview: 'Skills needing review',
    cachedSources: 'Cached sources',
    detectedAgents: 'Detected agents',
    diagnose: 'Diagnose',
    sources: 'Sources',
    addSource: 'Add Source',
    agents: 'Agents',
    detect: 'Detect',
    mcpServers: 'MCP Servers',
    detectMcp: 'Detect MCP',
    healthCheck: 'Health Check',
    recentSyncs: 'Recent Syncs',
    openRecords: 'Open Records',
    status: 'Status',
    skill: 'Skill',
    sourceLabel: 'Source',
    detail: 'Detail',
    agent: 'Agent',
    health: 'Health',
    server: 'Server',
    mode: 'Mode',
    destination: 'Destination',
    time: 'Time',
    notChecked: 'Not checked',
} as const;

const chineseMessages: Record<MessageKey, string> = {
    noSkillsFound: '未找到技能',
    initializeOrAddSkills: '初始化或添加技能',
    files: '个文件',
    path: '路径',
    score: '评分',
    size: '大小',
    updated: '更新于',
    issues: '问题',
    noSourcesConfigured: '未配置来源',
    addSourceUrl: '添加来源 URL',
    cached: '已缓存',
    notFetched: '未拉取',
    agentsNotDetectedYet: '尚未检测智能体',
    runDetectCommand: '运行检测命令',
    detected: '已检测',
    notDetected: '未检测',
    noMcpServersDetected: '未检测到 MCP 服务器',
    runDetectMcpServers: '运行 MCP 服务器检测',
    disabled: '已禁用',
    enabled: '已启用',
    tool: '工具',
    command: '命令',
    source: '来源',
    noSkillsFoundTable: '未找到技能。',
    tags: '标签',
    delete: '删除',
    noSourcesConfiguredTable: '未配置来源。',
    remove: '移除',
    agentsNotDetectedTable: '尚未检测智能体。',
    noSyncRecordsYet: '暂无同步记录。',
    noMcpServersTable: '未检测到 MCP 服务器。请运行 MCP 检测。',
    enable: '启用',
    disable: '禁用',
    sync: '同步',
    refresh: '刷新',
    updateSources: '更新来源',
    installSkill: '安装技能',
    syncToAgents: '同步到智能体',
    detectAgents: '检测智能体',
    backup: '备份',
    openRepository: '打开仓库',
    skills: '技能',
    skillsNeedingReview: '需检查技能',
    cachedSources: '已缓存来源',
    detectedAgents: '已检测智能体',
    diagnose: '诊断',
    sources: '来源',
    addSource: '添加来源',
    agents: '智能体',
    detect: '检测',
    mcpServers: 'MCP 服务器',
    detectMcp: '检测 MCP',
    healthCheck: '健康检查',
    recentSyncs: '最近同步',
    openRecords: '打开记录',
    status: '状态',
    skill: '技能',
    sourceLabel: '来源',
    detail: '详情',
    agent: '智能体',
    health: '健康状态',
    server: '服务器',
    mode: '模式',
    destination: '目标',
    time: '时间',
    notChecked: '未检查',
};

export function isChineseLanguage(): boolean {
    return vscode.env.language.toLowerCase().startsWith('zh');
}

export function t(key: MessageKey): string {
    return isChineseLanguage() ? chineseMessages[key] : englishMessages[key];
}

export function localize(english: string, chinese: string): string {
    return isChineseLanguage() ? chinese : english;
}
